---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ service.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  annotations:
    getambassador.io/config: |
{% if build.profile.name == "stable" %}
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{ build.name }}
      prefix: /
      host: hellospring.svc.datawire.io
      service: {{ build.name }}.{{ service.namespace }}
{% else %}
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{ build.name }}
      prefix: /
      host: {{ build.name }}.svc.datawire.io
      service: {{ build.name }}.{{ service.namespace }}
{% endif %}
spec:
  type: ClusterIP
  selector:
    app: {{ build.name }}
  ports:
    - name: http-api
      port: 80

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ build.name }}
    spec:
      containers:
        - name: kubernaut
          image: {{ build.images["Dockerfile"] }}
          env: []
          ports:
            - name: http-api
              containerPort: 8080
